l_arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 3
l_arm_group_position_only_ik:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 3
  position_only_ik: True
l_leg_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 3
r_leg_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 3
##both_legs_group:
  ##kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  ##kinematics_solver_search_resolution: 0.005
  ##kinematics_solver_timeout: 0.5
  ##kinematics_solver_attempts: 3
#all_appendages_group:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.5
  #kinematics_solver_attempts: 3
r_arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 1.0
  kinematics_solver_attempts: 3
r_arm_group_position_only_ik:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 1.0
  kinematics_solver_attempts: 3
  position_only_ik: True
l_arm_with_torso_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  kinematics_solver_attempts: 5
l_arm_with_torso_group_position_only_ik:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  kinematics_solver_attempts: 5
  position_only_ik: True
r_arm_with_torso_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  kinematics_solver_attempts: 5
r_arm_with_torso_group_position_only_ik:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  kinematics_solver_attempts: 5
  position_only_ik: True
#both_arms_with_torso_group:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 2.0
  #kinematics_solver_attempts: 5
#both_arms_group:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 2.0
  #kinematics_solver_attempts: 5
torso_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 3
#both_arms_subgrouped:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 1.0
  #kinematics_solver_attempts: 3
#both_arms_with_torso_subgrouped:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 2.0
  #kinematics_solver_attempts: 3